# fly.toml app configuration file generated for portfolio-website-server on 2024-04-30T13:40:56+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-website-server'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
